#!/bin/bash
intern=eDP-1
extern=HDMI-1

if xrandr | grep "$extern disconnected"; then
    xrandr --output eDP-1 --mode 2048x1152
else
    xrandr --output "$intern" --off --output "$extern" --auto
fi

feh --bg-fill /home/azer/wallpaper.jpg
