#!/bin/bash
intern=eDP-1
extern=HDMI-1

if xrandr | grep "$extern disconnected"; then
    xrandr --output "$intern" --mode 1920x1200
else
    xrandr --auto --output "$intern" --off 
fi

sh ~/.happy-desktop/bin/set-wallpaper
